### ISSUE TITLE
Failing build and unit test 

### ISSUE THREAD

**Issue by mjperrins** [cloud-native-toolkit/terraform-gitops-cp-event-streams-instance#13]
Failing build and unit test

**Comment by JyotiRani** [comment]
Common services are not running on CP4I and GitOps2 clusters, hence the test is failing. Test pass on Techzone cluster, so we might need to re-create the cluster and try again.

**Comment by JyotiRani** [comment]
Dependency on https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/820 issue

**Comment by JyotiRani** [comment]
Fixed the common services issue by cleaning up the cluster, now ES passed successfully.
