### ISSUE TITLE
Can we fix the failing module.yaml change

### ISSUE THREAD

**Issue by mjperrins** [cloud-native-toolkit/terraform-gitops-cp-event-streams-instance#14]
Can we fix the failing module.yaml change

**Comment by JyotiRani** [comment]
its fixed, but failing test, due to common services issue on the cluster. I've already raised an issue https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/820 to recreate the cluster.

**Comment by JyotiRani** [comment]
Fixed the common services issue on CP4I cluster, now ES passed successfully.
